### PR TITLE
feat: text to speech

### PR DESCRIPTION
**Pull request by thewh1teagle**
## Description
Convert text to speech using Bard API

## Motivation and Context
Using Bard text to speech is useful for self hosted assistant

## How Has This Been Tested?
Tested manually with different accounts

## Usage
```python
from bardapi import Bard

bard = Bard(token= '...' )
audio = bard.speech('Hello, I am bard! How can I assist you?', lang = 'en-US') # bytes audio
with open('bard_response.mp3', 'wb') as f:
    f.write(audio)
```
Now you can open the file and play it...

### CODE REVIEW

**Comment by Jishan76** [comment]
Doesn't works

**Comment by thewh1teagle** [comment]
@Jishan76
What do you mean it doesn't work?
You got error? the audio not playing?

**Comment by dsdanielpark** [comment]
I tested it, and it worked successfully. Where can I find more information about the "lang" argument? 

I would appreciate it if you could provide additional information about the options available for "lang". 

I will accept this pull request and take some time to think and make modifications to the structure. Thank you.
Thank you for your contribution!

**Comment by thewh1teagle** [comment]
@dsdanielpark 
From yesterday, bard API updated, and supports 40+ different languages including speaking.

List of languages:
https://support.google.com/bard/answer/13575153?hl=en

The language parameter should be one from the supported languages in format of 
- English
```
en-US
```
- Hebrew
```
iw-IL
```
not sure where we can find list of this format codes, or which languages supported except for these

**Comment by dsdanielpark** [comment]
Thank you for your contribution. 

Due to other projects, I couldn't properly keep up with the updates for Bard. I will make sure to conduct some tests with the terms listed on the checklist!

**Pull request merged**
